Made wall slide speed consistent across devices
ProntoStudios/RedRunner pull request #102
Opened 2019-11-30 23:46 UTC by cdaly333

This should make the wall slide the same on every client

2019-11-30 23:57 UTC, WilsonCWu requested changes

2019-11-30 23:57 UTC, WilsonCWu commented on Assets/Scripts/RedRunner/Characters/RedCharacter.cs
> +				Debug.Log("U: " + m_Rigidbody2D.velocity);
delete this print statement

2019-12-01 00:09 UTC, cdaly333 commented on Assets/Scripts/RedRunner/Characters/RedCharacter.cs
> +				Debug.Log("U: " + m_Rigidbody2D.velocity);
oops lol

2019-12-01 00:10 UTC, WilsonCWu approved these changes

2019-12-01 00:11 UTC, merged